title: Recent Posts
description: Erkut Evirgen - Software Engineer & Technology Consultant
author: Erkut Evirgen
github: https://github.com/eevirgen
about: Software Engineer & Technology Consultant @London, UK
disqus_shortname: erkSpace
google_analytics: UA-19234700-1
avatar_url: /static/img/avatar_erk.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-building
      link: "https://wisen.tech"
    - icon: fa-twitter
      link: "https://twitter.com/eevirgen"
    - icon: fa-linkedin
      link: "https://uk.linkedin.com/in/erkutevirgen"
    - icon: fa-instagram
      link: "http://instagram.com/eevirgen"
    - icon: fa-github
      link: "https://github.com/eevirgen"
    - icon: fa-envelope
      link: "mailto:erkut@erkut.me"

share:
  twitter_username: eevirgen
  fb_appid: 217469665438549

urls:
    - text: About Me
      url: /about/
    - text: Work Portfolio
      url: /work/

url: "https://erkut.me"
baseurl: ""
paginate: 5
per_page: 5
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
